# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.CharField(blank=b'true', default=b'', max_length=100)),
                ('lct', models.DecimalField(decimal_places=6, max_digits=10, null=b'true')),
                ('valor', models.CharField(blank=b'true', default=b'', max_length=100, verbose_name=b'resultado')),
                ('verificacion', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=b'true', default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(blank=b'true', max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descuento', models.DecimalField(blank=b'true', decimal_places=2, default=0, max_digits=5, null=b'true', verbose_name=b'descuento (%)')),
                ('valor_total_sin_descuento', models.DecimalField(blank=b'true', decimal_places=2, default=0, max_digits=8, null=b'true')),
                ('valor_total_con_descuento', models.DecimalField(blank=b'true', decimal_places=2, default=0, max_digits=8, null=b'true')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=200, verbose_name=b'Contacto (apellido, nombre)')),
                ('funcion', models.CharField(blank=b'true', max_length=100)),
                ('domicilio', models.CharField(blank=b'true', max_length=100)),
                ('localidad', models.CharField(blank=b'true', max_length=200)),
                ('telefono_fijo', models.CharField(blank=b'true', max_length=100)),
                ('telefono_movil', models.CharField(blank=b'true', max_length=100)),
                ('email', models.CharField(blank=b'true', max_length=100)),
                ('cuit', models.CharField(blank=b'true', max_length=13)),
                ('nota', models.CharField(blank=b'true', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=b'true', max_length=100)),
                ('cantidadMuestra', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=b'descuento (%)')),
                ('total_sin_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_con_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seleccionado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_matriz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatrizTecnicaLct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lct', models.DecimalField(decimal_places=6, max_digits=10)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Matriz')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_clave', models.CharField(blank=b'true', default=b'M-', max_length=100)),
                ('referencia', models.CharField(blank=b'true', max_length=20)),
                ('ingreso_muestra', models.CharField(blank=b'true', max_length=100, verbose_name=b'responsable ingreso de muestra')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name=b'fecha de ingreso al sistema')),
                ('cadena_custodia', models.CharField(blank=b'true', max_length=100, verbose_name=b'cadena de custodia')),
                ('rotulo', models.CharField(blank=b'true', max_length=100)),
                ('ubicacion', models.CharField(blank=b'true', max_length=100, verbose_name=b'ubicaci\xc3\xb3n')),
                ('sitio_muestreo', models.CharField(blank=b'true', max_length=100, verbose_name=b'sitio de muestreo')),
                ('muestreador', models.CharField(blank=b'true', max_length=100)),
                ('peso', models.CharField(blank=b'true', max_length=100, verbose_name=b's\xc3\xb3lido - peso de muestra (gr.)')),
                ('volumen', models.CharField(blank=b'true', max_length=100, verbose_name=b'l\xc3\xadquido - Vol\xc3\xbamen de muestra (lt.)')),
                ('caudal', models.CharField(blank=b'true', max_length=100, verbose_name=b'aire - Caudal, (lt/min, tiempo)')),
                ('preservacion', models.CharField(blank=b'true', max_length=100, verbose_name=b'Preservaci\xc3\xb3n - Conservaci\xc3\xb3n')),
                ('fecha_muestreo', models.DateField(default=datetime.date.today, verbose_name=b'fecha de muestro')),
                ('coordenada', models.CharField(blank=b'true', max_length=100, verbose_name=b'coordenadas de ubicaci\xc3\xb3n')),
                ('sistema_coordenada', models.CharField(blank=b'true', max_length=100, verbose_name=b'sistema de coordenada')),
                ('observacion', models.CharField(blank=b'true', max_length=100, verbose_name=b'observaci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra_Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=b'true', max_length=30, unique=True)),
                ('ultimo_valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_clave', models.CharField(blank=b'true', default=b'OT-', max_length=100)),
                ('referencia', models.CharField(blank=b'true', max_length=20)),
                ('descripcion', models.CharField(blank=b'true', max_length=100)),
                ('prioridad', models.CharField(blank=b'true', max_length=100)),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name=b'fecha de creaci\xc3\xb3n')),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(default=b'pendiente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ot_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('muestreo_propio', models.BooleanField(default=False)),
                ('nota_muestreo', models.CharField(blank=b'true', max_length=200)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Ot_Estado')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Item')),
                ('orden_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Orden_trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_par', models.CharField(max_length=100, verbose_name=b'Parametro')),
                ('familia', models.ForeignKey(blank=b'true', null=b'true', on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_parametro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_precio', models.DateField(default=datetime.date.today, verbose_name=b'Fecha del precio')),
                ('fuente_precio', models.CharField(blank=b'true', max_length=100, verbose_name=b'Fuente del precio')),
                ('seleccionado', models.BooleanField(default=False)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Matriz')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Parametro')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_precio', models.DateField(verbose_name=b'Fecha del precio')),
                ('fuente_precio', models.CharField(blank=b'true', max_length=100, verbose_name=b'Fuente del precio')),
                ('seleccionado', models.BooleanField(default=False)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Matriz')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPrecio_Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Parametro')),
                ('perfilPrecio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.PerfilPrecio')),
            ],
        ),
        migrations.CreateModel(
            name='Plantillas_Impresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_condiciones_comerciales', models.TextField(blank=b'true')),
                ('presupuesto_condiciones_tecnicas', models.TextField(blank=b'true')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_clave', models.CharField(blank=b'true', default=b'S-P', max_length=100)),
                ('referencia', models.CharField(blank=b'true', max_length=20)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today, verbose_name=b'fecha de solicitud')),
                ('fecha_vencimiento', models.DateField(blank=b'true', null=b'true', verbose_name=b'fecha de vencimiento')),
                ('fecha_envio', models.DateField(blank=b'true', null=b'true', verbose_name=b'fecha de envio')),
                ('fecha_aprobacion', models.DateField(blank=b'true', null=b'true', verbose_name=b'fecha de aprobacion')),
                ('descripcion', models.CharField(max_length=100)),
                ('observacion', models.CharField(blank=b'true', max_length=100)),
                ('descuento', models.DecimalField(blank=b'true', decimal_places=2, default=0, max_digits=5, null=b'true', verbose_name=b'descuento global (%)')),
                ('impresion_introduccion', models.TextField(blank=b'true')),
                ('impresion_nota_muestreo', models.TextField(blank=b'true')),
                ('impresion_condiciones_comerciales', models.TextField(blank=b'true')),
                ('impresion_condiciones_tecnicas', models.TextField(blank=b'true')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Subitem_parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Item')),
                ('itemparametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.ParametroPrecio')),
            ],
        ),
        migrations.CreateModel(
            name='Subitem_perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Item')),
                ('itemperfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.PerfilPrecio')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tec', models.CharField(max_length=100, verbose_name=b'Tecnica')),
                ('derivacion', models.CharField(blank=b'true', max_length=100)),
                ('link', models.CharField(blank=b'true', max_length=100)),
                ('observacion', models.TextField(blank=b'true')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, verbose_name=b'Unidades')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Tipo'),
        ),
        migrations.AddField(
            model_name='perfilprecio_parametro',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Tecnica'),
        ),
        migrations.AddField(
            model_name='parametroprecio',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Tecnica'),
        ),
        migrations.AddField(
            model_name='orden_trabajo',
            name='presupuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Presupuesto'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Muestra_Estado'),
        ),
        migrations.AddField(
            model_name='muestra',
            name='ot_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Ot_Item'),
        ),
        migrations.AddField(
            model_name='matriztecnicalct',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Parametro'),
        ),
        migrations.AddField(
            model_name='matriztecnicalct',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Tecnica'),
        ),
        migrations.AddField(
            model_name='matriztecnicalct',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Unidades'),
        ),
        migrations.AddField(
            model_name='item',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Matriz'),
        ),
        migrations.AddField(
            model_name='item',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Presupuesto'),
        ),
        migrations.AddField(
            model_name='campania',
            name='presupuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Presupuesto'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Muestra'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Parametro'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.Tecnica'),
        ),
    ]
