# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='referencia_clave',
            field=models.CharField(blank=b'true', default=b'ID16-', max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='referencia_clave',
            field=models.CharField(blank=b'true', default=b'SP16-', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='matriztecnicalct',
            unique_together=set([('matriz', 'parametro', 'tecnica')]),
        ),
    ]
